<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Login
    </title>
</head>

<body>
    <h2>Login form</h2>
    <form action="/login" method="post">
        Login
        <input type="text" name="username">
        <br>
        Password
        <input type="password" name="password">
        <br>
        <input type="submit" value="Login">
    </form>

    <a href="/registration/driver"><h3>Registration driver</h3></a>
    <a href="/registration/passenger"><h3>Registration passenger</h3></a>
</body>

</html>
