<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Login
    </title>
</head>

<body>
<h2>Registration form</h2>
<form action="/registration/driver" method="post">
    Login
    <input type="text" name="login">
    <br>
    Password
    <input type="password" name="password">
    <br>

<#--    First Name-->
<#--    <input type="text" name="firstName">-->
<#--    <br>-->
<#---->
<#--    Last Name-->
<#--    <input type="text" name="lastName">-->
<#--    <br>-->
<#---->
<#--    Birth Date-->
<#--    <input type="date" name="birthDate">-->
<#--    <br>-->
<#---->
<#--    Phone Number-->
<#--    <input type="text" name="phoneNumber">-->
<#--    <br>-->
<#---->
    <input type="submit" value="Registration">
</form>

</body>

</html>
