create table users
(
    id           bigint generated by default as identity not null primary key,
    login        varchar(255)                            not null unique,
    password     varchar(255)                            not null,
    first_name   varchar(255),
    second_name  varchar(255),
    role_id      bigint                                  not null
);

create table user_roles
(
    id           bigint generated by default as identity not null primary key,
    role         varchar(255)                            not null unique
);

alter table users add constraint fk_users_user_roles foreign key(role_id) references user_roles;