-- INSERT INTO public.user_roles(role)
-- VALUES ('ROLE_ADMIN');
--
-- INSERT INTO public.user_roles(role)
-- VALUES ('ROLE_DRIVER');
--
-- INSERT INTO public.user_roles(role)
-- VALUES ('ROLE_PASSENGER');